version: '3.8'

services:
  web:
    build: 
      context: ./web
    container_name: air_quality_app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://airuser:airpassword@db/air_quality_db
      - FLASK_APP=app.py
    depends_on:
      - db

  db:
    image: postgres:17-bookworm
    container_name: my_postgres
    restart: always
    environment:
      - POSTGRES_USER=airuser
      - POSTGRES_PASSWORD=airpassword
      - POSTGRES_DB=air_quality_db
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airuser -d air_quality_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
